FROM --platform=linux/amd64 python:3.12-slim

ENV PYTHONUNBUFFERED=1

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    ca-certificates \
    netcat-openbsd \
 && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir antithesis

COPY health-checker/entrypoint.py /entrypoint.py
RUN chmod +x /entrypoint.py

ENTRYPOINT ["/entrypoint.py"]
